main : com.boyboy0710.mob.Main
name : mob
version : 1.5.0
api-version : 1.16

commands:
  spawn:
    king_zombie:
    king_skeleton:
    king_Wither Skeleton:
    king_creeper:
  spawn_no_ai:
